### ISSUE TITLE
Not sure how to execute external scripts

### ISSUE THREAD

**Issue by e14mattc** [usernamehw/vscode-run-commands-view#3]
I've had a poke through the source, and looked at all your examples, but don't see how to add settings for running an arbitrary script (.cmd, .exe or whatever) on Windows. 

Ideally I'd also want to pass in the name of the file I'm executing the script against, and maybe the line of code my cursor is on.

This is the same kind of thing implemented in Notepad++
http://docs.notepad-plus-plus.org/index.php/External_Programs

**Comment by usernamehw** [comment]
Best you can do ATM is to send something to terminal:
```json
"☢ chrome": {
    "command": "workbench.action.terminal.sendSequence",
    "args": { "text" : "\"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe\"\u000D"}
},
```

**Comment by usernamehw** [comment]
The extension is able to run commands contributed by other extensions, so I suggest to try and search for an extension that can do what you want at marketplace https://marketplace.visualstudio.com/vscode

If there is none - this can stay as 2 feature requests: 
- Run commands without terminal
- Parse variables from command `args`

**Comment by e14mattc** [comment]
That 'sendSequence' example is great; it'd be good to add that to the README.md. 

But you can't pass in the current file path into args, right? That would make this extension super-useful if it could.

**Comment by usernamehw** [comment]
I have a feeling that we're reinventing the wheel. Can you take a look at [Tasks](https://code.visualstudio.com/docs/editor/tasks)?

```json
{
    "version": "2.0.0",
    "tasks": [
        {
			"label": "Run tests",
			"options": {
				"shell": {
					"executable": "cmd.exe",
					"args": [
						"/d", "/c"
					]
				}
			},
            "type": "shell",
            "command": "ls",
            "windows": {
                "command": "start chrome"
			},
			"args": [
				"--disk-cache-size=104857600"
			],
            "group": "test",
            "presentation": {
                "reveal": "always",
				"panel": "new",
			}
        }
    ]
}
```

### They already have a bunch of [variables](https://code.visualstudio.com/docs/editor/variables-reference):

* `${workspaceFolder}` - the path of the folder opened in VS Code
* `${workspaceFolderBasename}` - the name of the folder opened in VS Code without any slashes (/)
* `${file}` - the current opened file
* `${relativeFile}` - the current opened file relative to workspaceFolder
* `${fileBasename}` - the current opened file's basename
* `${fileBasenameNoExtension}` - the current opened file's basename with no file extension
* `${fileDirname}` - the current opened file's dirname
* `${fileExtname}` - the current opened file's extension
* `${cwd}` - the task runner's current working directory on startup
* `${lineNumber}` - the current selected line number in the active file
* `${selectedText}` - the current selected text in the active file
* `${execPath}` - the path to the running VS Code executable

### Environment variables:

```json
{
    "type": "node",
    "request": "launch",
    "name": "Launch Program",
    "program": "${workspaceFolder}/app.js",
    "cwd": "${workspaceFolder}",
    "args": [ "${env:USERNAME}" ]
}
```

### Configuration variables
```
${config:editor.fontSize}
```

### Binding keyboard shortcuts to tasks
If you need to run a task frequently, you can define a keyboard shortcut for the task.

For example, to bind <kbd>Ctrl</kbd>+<kbd>H</kbd> to the Run tests task from above, add the following to your keybindings.json file:
```json
{
    "key": "ctrl+h",
    "command": "workbench.action.tasks.runTask",
    "args": "Run tests"
}
```
and other stuff. Currently not possible to have global tasks https://github.com/Microsoft/vscode/issues/1435 , but it has 132 upvotes, so ... probably will be implemented soon.

**Comment by e14mattc** [comment]
Yup, you're right. I had a look into tasks & it practically does everything I need for running external scripts (as I try to migrate over from Notepad++). Thanks for all your help.. much appreciated.

**Comment by usernamehw** [comment]
I'm going to close this since vscode supports global tasks from around ~**1.42** version and no work planned on duplicating this feature.
