### ISSUE TITLE
Examples to run in terminal

### ISSUE THREAD

**Issue by pegaltier** [usernamehw/vscode-run-commands-view#5]
I would like to be able to do different things with the terminal:
- run a command with argument in the current terminal
- open a new terminal a lunch a command with arguments

ex for npm scripts

Thanks

**Comment by usernamehw** [comment]
```js
"run-commands-view.commands": {
    "1️⃣ run in teminal": {
        "command": "workbench.action.terminal.sendSequence",
        "args": {
            "text": "npm run test\r"
        }
    },
    "2️⃣ create new teminal": {
        "sequence": [
            {
                "command": "workbench.action.terminal.new"
            },
            {
                "command": "workbench.action.terminal.sendSequence",
                "args": {
                    "text": "npm run test\r"
                }
            }
        ]
    },
}
```

**Comment by pegaltier** [comment]
Yes i have found also by myself the commands, it's very nice, I also use:"workbench.action.terminal.split", to execute thing in parallel :) Thank you very much. Maybe we can add this to the readme. Anyway good job!

**Comment by usernamehw** [comment]
Do you want to make a PR (documenting terminal command)?

**Comment by pegaltier** [comment]
Done: https://github.com/usernamehw/vscode-run-commands-view/pull/6

**Comment by usernamehw** [comment]
Fixed by #6

**Comment by rehierl** [comment]
I'm having a little bit of an issue with the `workbench.action.terminal.new` command: Each time I run the "new" command, vscode pops open a dialog asking me to select a working directory for the new terminal. Is there any way to pass a directory to the command by using the `args` property, or let it automatically use the `${workspaceFolder}` environment variable?

Please note that this won't happen, if only one workspace folder is open in the Explorer panel.

**Comment by usernamehw** [comment]
I've never seen that dialog. Is it multi-root workspace? Maybe `workbench.action.terminal.newInActiveWorkspace` command would work in that case?

**Comment by usernamehw** [comment]
Or maybe like that:

```js
"command": "workbench.action.terminal.newWithCwd",
"args": {
	"cwd": "${fileDirname}"
}
```

**Comment by rehierl** [comment]
> Is it multi-root workspace?

I'm using the [workspace explorer](https://marketplace.visualstudio.com/items?itemName=tomsaunders.vscode-workspace-explorer) extension.

> `.newInActiveWorkspace`

That did work. I missed that action in the keyboard shortcut listing.

> `.newWithCwd`

That did work as well.

Thank you so much!
