### ISSUE TITLE
FEATURE REQUEST: Incorporate VS Code UI Icons

### ISSUE THREAD

**Issue by john-hillert** [usernamehw/vscode-run-commands-view#7]
Hi, 
There is another extension "[Commands](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-commands)" that is like this one except that commands are added to status bar.  That one allows icons from [this list](https://code.visualstudio.com/api/references/icons-in-labels), to be part of the display name.  Syntax to be used inside quotes is $(), so like: 
    "$(three-bars) Menu" 
would look like this: 
    ≡ Menu

Can this functionality be added to vscode-run-commands-view?

**Comment by usernamehw** [comment]
From version **0.4.2**

```js
"$(zap|zapcolor) Zap": "workbench.action.toggleStatusbarVisibility",
"$(flame|errorForeground) Flame": "workbench.action.toggleStatusbarVisibility",
```

Optionally, define colors (in `settings.json`)
```js
"workbench.colorCustomizations": {
	"zapcolor": "#fff000",
},
```
