### ISSUE TITLE
How to run tasks?

### ISSUE THREAD

**Issue by GitMensch** [usernamehw/vscode-run-commands-view#8]
I failed to deduce this from the documentation.

**Comment by GitMensch** [comment]
Possibly something like

```json
"▶️ Run Task": {
	"command": "workbench.action.tasks.runTask",
	"args": { "MyTask" }
},
```

???

**Comment by usernamehw** [comment]
It has the same syntax as running something from `keybindings.json` file.

`tasks.json`

```js
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "hello",
			"type": "shell",
			"command": "echo hello"
		}
	]
}
```

`settings.json`

```js
"run-commands-view.commands": {
    "hello": {
        "command": "workbench.action.tasks.runTask",
        "args": "hello"
    },
}
```

https://code.visualstudio.com/docs/editor/tasks#_binding-keyboard-shortcuts-to-tasks

**Comment by GitMensch** [comment]
Can you add this to the README along the other samples?

**Comment by usernamehw** [comment]
Not sure. I would rather add a link to the list of all vscode commands that support arguments. There's a page, but it's missing too many: https://code.visualstudio.com/api/references/commands. Maybe someone will document it in the future: https://github.com/microsoft/vscode-docs/issues/4298

If you still want to make a PR with run task example - I will merge it.

**Comment by GitMensch** [comment]
> If you still want to make a PR with run task example - I will merge it.

Thank you, did so with #9.


Note: when testing this I've seen that it works as it is described but it currently does not with a space in the argument name.
Definition in `tasks.json` works and can be run via terminal->run task

```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "hi you",
			"type": "shell",
			"command": "echo hello"
		}
	]
}
```

But neither of these entries in `settings.json` work - they all open the "choose task" menu:

```json
"run-commands-view.commands": {
    "hello": {
        "command": "workbench.action.tasks.runTask",
        "args": "hi you"
    },
    "hello2": {
        "command": "workbench.action.tasks.runTask",
        "args": "\"hi you\""
    },
    "hello2": {
        "command": "workbench.action.tasks.runTask",
        "args": "hi\\ you"
    },
}
```

Do you have a hint (or fix) to also allow tasks that contain multiple names?

**Comment by usernamehw** [comment]
It works for me when using it with spaces:

```js
"hello": {
	"command": "workbench.action.tasks.runTask",
	"args": "hi you"
},
```

Do you use global or workspace `tasks.json`? Does it also fail when you try to call it from a shortcut - `keybindings.json`:

```js
{
	"key": "ctrl+shift+9",
	"command": "workbench.action.tasks.runTask",
	"args": "hi you"
}
```
